#!/bin/bash

# ==============================================================================
# setup-worker.sh
#
# Description: Configures an Ubuntu machine to be a Kubernetes worker node.
#              This script is intended to be run with arguments generated by
#              the companion `generate-worker-args.sh` script. It now uses
#              pre-approved client certificates for the kubelet, removing the
#              need for manual CSR approval on the control plane after setup.
#              It also installs an admin kubeconfig for local `kubectl` use.
#
# Usage: See the --help flag.
# ==============================================================================

set -euo pipefail

# --- Default values ---
NODE_NAME=""
API_SERVER_URL=""
CLUSTER_CA_CERT_BASE64=""
NODE_PRIVATE_KEY_BASE64=""
NODE_CLIENT_CERT_BASE64=""
LOCAL_EDIT_PRIVATE_KEY_BASE64=""
LOCAL_EDIT_CLIENT_CERT_BASE64=""
CLUSTER_DNS_IP="10.96.0.10"
VERSION="" # New required argument for Kubernetes version
CONTAINERD_VERSION="1.7.22" # Default value, can be overridden by argument
CNI_PLUGINS_VERSION="1.5.1" # Default value, can be overridden by argument (without 'v')
PROVIDER="gcp" # Default provider

# --- Argument Parsing ---
print_usage() {
    echo "Usage: $0 --name <node-name> --api-url <k8s-api-url> --ca-cert-base64 <ca-cert> --node-private-key-base64 <node-key> --node-client-cert-base64 <node-cert> --local-edit-private-key-base64 <local-edit-key> --local-edit-client-cert-base64 <local-edit-cert> --cluster-dns-ip <dns-ip> --version <k8s-version> [--containerd-version <version>] [--cni-version <version>] [--provider <gcp|aws>]"
}

while [[ "$#" -gt 0 ]]; do
    case $1 in
        --name) NODE_NAME="$2"; shift ;;
        --api-url) API_SERVER_URL="$2"; shift ;;
        --ca-cert-base64) CLUSTER_CA_CERT_BASE64="$2"; shift ;;
        --node-private-key-base64) NODE_PRIVATE_KEY_BASE64="$2"; shift ;;
        --node-client-cert-base64) NODE_CLIENT_CERT_BASE64="$2"; shift ;;
        --local-edit-private-key-base64) LOCAL_EDIT_PRIVATE_KEY_BASE64="$2"; shift ;;
        --local-edit-client-cert-base64) LOCAL_EDIT_CLIENT_CERT_BASE64="$2"; shift ;;
        --cluster-dns-ip) CLUSTER_DNS_IP="$2"; shift ;;
        --version) VERSION="$2"; shift ;;
        --containerd-version) CONTAINERD_VERSION="$2"; shift ;;
        --cni-version) CNI_PLUGINS_VERSION="$2"; shift ;;
        --provider) PROVIDER="$2"; shift ;;
        --help) print_usage; exit 0 ;;
        *) echo "Unknown parameter passed: $1"; print_usage; exit 1 ;;
    esac
    shift
done

if [[ "$PROVIDER" != "gcp" && "$PROVIDER" != "aws" ]]; then
    echo "Error: Invalid provider '$PROVIDER'. Must be 'gcp' or 'aws'."
    exit 1
fi

if [ -z "$NODE_NAME" ] || \
   [ -z "$API_SERVER_URL" ] || \
   [ -z "$CLUSTER_CA_CERT_BASE64" ] || \
   [ -z "$NODE_PRIVATE_KEY_BASE64" ] || \
   [ -z "$NODE_CLIENT_CERT_BASE64" ] || \
   [ -z "$LOCAL_EDIT_PRIVATE_KEY_BASE64" ] || \
   [ -z "$LOCAL_EDIT_CLIENT_CERT_BASE64" ] || \
   [ -z "$VERSION" ]; then
    echo "Error: Missing required arguments."
    print_usage
    exit 1
fi

# Sanitize input versions by removing leading 'v'
VERSION="${VERSION#v}"
CONTAINERD_VERSION="${CONTAINERD_VERSION#v}"
CNI_PLUGINS_VERSION="${CNI_PLUGINS_VERSION#v}"

AWS_REGION=""
AWS_ZONE=""
if [ "$PROVIDER" = "aws" ]; then
    echo "--> Detecting AWS region and availability zone..."
    # IMDSv2 requires a token
    TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
    if [ -z "$TOKEN" ]; then
        echo "    [i] Failed to get IMDSv2 token. Trying IMDSv1..."
        AWS_ZONE=$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
    else
        AWS_ZONE=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/placement/availability-zone)
    fi
    
    if [ -z "$AWS_ZONE" ]; then
        echo "Error: Failed to detect AWS availability zone. Please ensure this node is running in AWS."
        exit 1
    fi
    # Region is zone minus the last letter
    AWS_REGION="${AWS_ZONE%?}"
    echo "  [✓] Detected AWS Region: ${AWS_REGION}, Zone: ${AWS_ZONE}"
fi

echo "--- Starting Kubernetes Worker Node Setup for ${NODE_NAME} (K8s Version: ${VERSION}, Containerd: ${CONTAINERD_VERSION}, CNI: ${CNI_PLUGINS_VERSION}) ---"

# Determine architecture for containerd and CNI plugins
echo "  --> Determining architecture..."
MACHINE_ARCH=$(uname -m)
ARCH=""

case "$MACHINE_ARCH" in
    "x86_64")
        ARCH="amd64"
        ;;
    "aarch64")
        ARCH="arm64"
        ;;
    *)
        echo "Error: Unsupported machine architecture: $MACHINE_ARCH. Expected x86_64 (amd64) or aarch64 (arm64)."
        exit 1
        ;;
esac
echo "  [✓] Detected architecture: ${ARCH}"

# --- Step 1: System Preparation ---
echo "--> [1/7] Preparing system: disabling swap, loading kernel modules, and configuring sysctl parameters..."
swapoff -a
sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

# Load kernel modules required for container networking and CNI (e.g., overlayfs for containerd, br_netfilter for kube-proxy/CNI)
echo "  --> Loading overlay and br_netfilter kernel modules..."
modprobe overlay || { echo "Warning: Failed to load overlay module."; }
modprobe br_netfilter || { echo "Warning: Failed to load br_netfilter module."; }
echo "  [✓] Kernel modules loaded."

# Configure sysctl parameters for Kubernetes networking
echo "  --> Configuring sysctl parameters for Kubernetes..."
mkdir -p /etc/sysctl.d/
cat <<EOF | tee /etc/sysctl.d/kubernetes.conf > /dev/null
net.bridge.bridge-nf-call-iptables=1
net.ipv4.ip_forward=1
net.bridge.bridge-nf-call-ip6tables=1
EOF
sysctl --system > /dev/null # Apply settings from all files in /etc/sysctl.d/
echo "  [✓] Sysctl parameters configured."
echo "  [✓] System prepared."

# --- Step 2: Install CNI Plugins ---
echo "--> [2/7] Installing CNI plugins..."
mkdir -p /opt/cni/bin
CNI_PLUGINS_URL="https://github.com/containernetworking/plugins/releases/download/v${CNI_PLUGINS_VERSION}/cni-plugins-linux-${ARCH}-v${CNI_PLUGINS_VERSION}.tgz"
curl -sL "${CNI_PLUGINS_URL}" -o cni-plugins.tgz
if [ ! -f cni-plugins.tgz ]; then
    echo "Error: Downloaded cni-plugins.tgz not found. Exiting."
    exit 1
fi
echo "  --> Extracting CNI plugins..."
tar -xvf cni-plugins.tgz -C /opt/cni/bin >/dev/null
rm cni-plugins.tgz
echo "  [✓] CNI plugins installed."

# --- Step 3: Install Container Runtime (containerd) ---
echo "--> [3/7] Installing containerd runtime..."

echo "  --> Downloading containerd for ${ARCH} (version ${CONTAINERD_VERSION})..."
# Use -sL for silent and follow redirects
curl -sL "https://github.com/containerd/containerd/releases/download/v${CONTAINERD_VERSION}/cri-containerd-${CONTAINERD_VERSION}-linux-${ARCH}.tar.gz" -o containerd.tar.gz
if [ ! -f containerd.tar.gz ]; then
    echo "Error: Downloaded containerd.tar.gz not found. Exiting."
    exit 1
fi

echo "  --> Extracting containerd..."
# This command typically extracts binaries to /usr/local/bin, configs to /etc/containerd, and service files to /etc/systemd/system
tar -xvf containerd.tar.gz -C / >/dev/null

# Clean up the downloaded tarball
rm containerd.tar.gz

echo "  --> Configuring containerd (ensuring systemd cgroup driver)..."
# Ensure /etc/containerd/config.toml exists (it usually does, but good to be safe)
if [ ! -f /etc/containerd/config.toml ]; then
    echo "  [W] /etc/containerd/config.toml not found after extraction. Generating default..."
    mkdir -p /etc/containerd
    /usr/local/bin/containerd config default > /etc/containerd/config.toml
fi
# Ensure cgroup driver is set to systemd, which is required for K8s
sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml

# Reload systemd daemon to pick up new service files (if any)
systemctl daemon-reload

echo "  --> Enabling and starting containerd service..."
systemctl enable containerd
systemctl restart containerd
echo "  [✓] Containerd installed, configured, and service started."

# --- Step 4: Install Kubernetes Components ---
echo "--> [4/7] Installing kubelet and kubectl..."

echo "  --> Checking for and removing existing kubelet and kubectl binaries..."
if [ -f /usr/bin/kubelet ]; then
    echo "    [i] Found existing /usr/bin/kubelet. Removing..."
    rm -f /usr/bin/kubelet
fi
if [ -f /usr/bin/kubectl ]; then
    echo "    [i] Found existing /usr/bin/kubectl. Removing..."
    rm -f /usr/bin/kubectl
fi
echo "  [✓] Existing Kubernetes binaries removed (if present)."

# Download kubelet
KUBELET_DOWNLOAD_URL="https://dl.k8s.io/release/v${VERSION}/bin/linux/${ARCH}/kubelet"
echo "  --> Downloading kubelet from ${KUBELET_DOWNLOAD_URL}..."
if ! curl -sL "${KUBELET_DOWNLOAD_URL}" -o /usr/bin/kubelet; then # Download to /usr/bin to match ExecStart path
    echo "Error: Failed to download kubelet from ${KUBELET_DOWNLOAD_URL}. Exiting."
    exit 1
fi
chmod +x /usr/bin/kubelet

# Download kubectl
KUBECTL_DOWNLOAD_URL="https://dl.k8s.io/release/v${VERSION}/bin/linux/${ARCH}/kubectl"
echo "  --> Downloading kubectl from ${KUBECTL_DOWNLOAD_URL}..."
if ! curl -sL "${KUBECTL_DOWNLOAD_URL}" -o /usr/bin/kubectl; then # Download to /usr/bin
    echo "Error: Failed to download kubectl from ${KUBECTL_DOWNLOAD_URL}. Exiting."
    exit 1
fi
chmod +x /usr/bin/kubectl

echo "  [✓] Kubernetes components installed."

# --- Step 5: Configure Kubernetes Directories and Credentials ---
echo "--> [5/7] Placing credentials and kubeconfig files..."
mkdir -p /var/lib/kubelet /etc/kubernetes/pki

# Decode and place kubelet credentials
echo "${CLUSTER_CA_CERT_BASE64}" | base64 -di > /etc/kubernetes/pki/ca.crt
echo "${NODE_PRIVATE_KEY_BASE64}" | base64 -di > "/var/lib/kubelet/${NODE_NAME}.key"
echo "${NODE_CLIENT_CERT_BASE64}" | base64 -di > "/var/lib/kubelet/${NODE_NAME}.crt"
chmod 600 "/var/lib/kubelet/${NODE_NAME}.key"
chmod 644 "/var/lib/kubelet/${NODE_NAME}.crt" # Client cert can be readable by kubelet

# Decode and place local-edit credentials
echo "  --> Placing kubernetes-local-edit credentials..."
echo "${LOCAL_EDIT_PRIVATE_KEY_BASE64}" | base64 -di > "/etc/kubernetes/local-edit.key"
echo "${LOCAL_EDIT_CLIENT_CERT_BASE64}" | base64 -di > "/etc/kubernetes/local-edit.crt"
chmod 600 "/etc/kubernetes/local-edit.key"
chmod 644 "/etc/kubernetes/local-edit.crt"


# Create kubelet.kubeconfig
# The kubeconfig for kubelet will now contain the pre-signed client certificate and key.
kubectl config set-cluster k8s-manual --server="${API_SERVER_URL}" --certificate-authority=/etc/kubernetes/pki/ca.crt --kubeconfig=/var/lib/kubelet/kubeconfig --embed-certs=true >/dev/null
# Use both client certificate and client key directly
kubectl config set-credentials "system:node:${NODE_NAME}" --client-certificate="/var/lib/kubelet/${NODE_NAME}.crt" --client-key="/var/lib/kubelet/${NODE_NAME}.key" --kubeconfig=/var/lib/kubelet/kubeconfig --embed-certs=true >/dev/null
kubectl config set-context default --cluster=k8s-manual --user="system:node:${NODE_NAME}" --kubeconfig=/var/lib/kubelet/kubeconfig >/dev/null
kubectl config use-context default --kubeconfig=/var/lib/kubelet/kubeconfig >/dev/null

# Fix: Create /etc/kubernetes/bootstrap-kubelet.conf to satisfy stat check
# Since we are using pre-signed certs, the kubelet directly uses --kubeconfig=/var/lib/kubelet/kubeconfig.
# This file is copied for compatibility, as some tools or older kubelet setups might expect bootstrap-kubelet.conf to exist.
mkdir -p /etc/kubernetes
cp /var/lib/kubelet/kubeconfig /etc/kubernetes/bootstrap-kubelet.conf
echo "  [✓] Created /etc/kubernetes/bootstrap-kubelet.conf"


# Create /etc/kubernetes/local-edit.conf for general kubectl usage on the node
echo "  --> Creating /etc/kubernetes/local-edit.conf for kubectl..."
kubectl config set-cluster k8s-manual --server="${API_SERVER_URL}" --certificate-authority=/etc/kubernetes/pki/ca.crt --kubeconfig=/etc/kubernetes/local-edit.conf --embed-certs=true >/dev/null
kubectl config set-credentials kubernetes-local-edit --client-certificate="/etc/kubernetes/local-edit.crt" --client-key="/etc/kubernetes/local-edit.key" --kubeconfig=/etc/kubernetes/local-edit.conf --embed-certs=true >/dev/null
kubectl config set-context default --cluster=k8s-manual --user=kubernetes-local-edit --kubeconfig=/etc/kubernetes/local-edit.conf >/dev/null
kubectl config use-context default --kubeconfig=/etc/kubernetes/local-edit.conf >/dev/null
echo "  [✓] /etc/kubernetes/local-edit.conf created."


echo "  [✓] Credentials and kubeconfigs created."

# --- Step 6: Configure Kubelet Service ---
echo "--> [6/7] Creating kubelet configuration and systemd service..."

# Clean up any kubeadm-generated drop-ins for kubelet service.
# This prevents conflicting configurations like bootstrap-kubeconfig environment variables.
echo "  --> Removing existing kubelet service drop-in configurations..."
rm -rf /etc/systemd/system/kubelet.service.d/*
echo "  [✓] Cleaned up old kubelet service configurations."

# CNI network configuration is now managed by the chosen CNI provider (e.g., Cilium)
# and should not be manually created here.
# The `/etc/cni/net.d` directory will be populated by the cluster's CNI deployment.

# Kubelet config file
cat > /var/lib/kubelet/config.yaml <<EOF
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
cgroupDriver: "systemd"
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: true
  x509:
    clientCAFile: "/etc/kubernetes/pki/ca.crt"
authorization:
  mode: Webhook
clusterDNS:
  - "${CLUSTER_DNS_IP}"
clusterDomain: "cluster.local"
rotateCertificates: true # Keep this, as it's good for automatic certificate renewals later.
tlsCertFile: "/var/lib/kubelet/${NODE_NAME}.crt"
tlsPrivateKeyFile: "/var/lib/kubelet/${NODE_NAME}.key"
EOF

# Kubelet systemd service file
KUBELET_LABELS="node.kubernetes.io/kube-proxy-ds-ready=true"
if [ "$PROVIDER" = "aws" ]; then
    KUBELET_LABELS="${KUBELET_LABELS},topology.kubernetes.io/region=${AWS_REGION},topology.kubernetes.io/zone=${AWS_ZONE}"
fi

EXEC_START="/usr/bin/kubelet --config=/var/lib/kubelet/config.yaml --kubeconfig=/var/lib/kubelet/kubeconfig --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock --register-node=true --node-labels=${KUBELET_LABELS} --v=2"

if [ "$PROVIDER" = "aws" ]; then
    EXEC_START="${EXEC_START} --cloud-provider=external"
fi

cat > /etc/systemd/system/kubelet.service <<EOF
[Unit]
Description=Kubernetes Kubelet
Documentation=https://github.com/kubernetes/kubernetes
After=containerd.service
Requires=containerd.service

[Service]
ExecStart=${EXEC_START}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

echo "  [✓] Kubelet service configured."

# --- Step 7: Start Services ---
echo "--> [7/7] Enabling and starting kubelet services..."
systemctl daemon-reload
systemctl enable kubelet
systemctl restart kubelet
echo "  [✓] Kubelet service started."
echo
echo "------------------------------------------------------------------------"
echo "  [SUCCESS] Worker node setup is complete."
echo "  Please ensure your CNI (e.g., Cilium) and kube-proxy (e.g., as a DaemonSet) are installed on the cluster from your control plane."
echo "  To use kubectl on this node with 'edit' permissions, run: export KUBECONFIG=/etc/kubernetes/local-edit.conf"
echo "  Remember to create the ClusterRoleBinding on the control plane if not already done:"
echo "  kubectl create clusterrolebinding kubernetes-local-edit-binding --clusterrole=edit --group=kubernetes:edit-users"
echo "------------------------------------------------------------------------"