# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1 # You can change the number of desired replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest # Using the latest NGINX image. You can specify a version like nginx:1.23.3
        ports:
        - containerPort: 80 # NGINX default port
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx # This selects the pods created by the nginx-deployment
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # The port the service listens on
      targetPort: 80 # The port on the pod to which the service sends traffic
      