#!/usr/bin/env python3

import argparse
import base64
import json
import os
import shutil
import subprocess
import sys
import urllib.request

def run_command(command, shell=False, check=True, text=True, capture_output=True):
    try:
        result = subprocess.run(
            command, shell=shell, check=check, text=text,
            capture_output=capture_output
        )
        return result.stdout.strip() if result.stdout else ""
    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {command}")
        print(f"Stdout: {e.stdout}")
        print(f"Stderr: {e.stderr}")
        if check:
            sys.exit(1)
        return None

def safe_b64decode(s):
    s = s.strip().replace("\n", "").replace(" ", "")
    padding = len(s) % 4
    if padding > 0:
        s += "=" * (4 - padding)
    return base64.b64decode(s)

def main():
    parser = argparse.ArgumentParser(description="Configure NixOS machine as a Kubernetes worker node.")
    parser.add_argument("--name", required=True)
    parser.add_argument("--api-url", required=True)
    parser.add_argument("--ca-cert-base64", required=True)
    parser.add_argument("--node-private-key-base64", required=True)
    parser.add_argument("--node-client-cert-base64", required=True)
    parser.add_argument("--local-edit-private-key-base64", required=True)
    parser.add_argument("--local-edit-client-cert-base64", required=True)
    parser.add_argument("--cluster-dns-ip", required=True)
    parser.add_argument("--pod-cidr")
    parser.add_argument("--version", required=True)
    parser.add_argument("--provider", choices=["gcp", "aws", "azure"], default="gcp")
    parser.add_argument("--labels")
    parser.add_argument("--provider-id")

    args = parser.parse_args()

    if os.geteuid() != 0:
        print("Error: This script must be run as root (sudo).")
        sys.exit(1)

    node_name = args.name
    provider = args.provider

    print(f"--- Starting NixOS Kubernetes Worker Node Setup for {node_name} ---")

    # Step 1: Place Credentials
    print("--> [1/4] Placing credentials...")
    os.makedirs("/etc/kubernetes/pki", exist_ok=True)
    os.makedirs("/var/lib/kubelet", exist_ok=True)

    with open("/etc/kubernetes/pki/ca.crt", "wb") as f:
        f.write(safe_b64decode(args.ca_cert_base64))
    with open(f"/var/lib/kubelet/node.key", "wb") as f:
        f.write(safe_b64decode(args.node_private_key_base64))
    with open(f"/var/lib/kubelet/node.crt", "wb") as f:
        f.write(safe_b64decode(args.node_client_cert_base64))
    
    with open("/etc/kubernetes/local-edit.key", "wb") as f:
        f.write(safe_b64decode(args.local_edit_private_key_base64))
    with open("/etc/kubernetes/local-edit.crt", "wb") as f:
        f.write(safe_b64decode(args.local_edit_client_cert_base64))
    
    os.chmod("/var/lib/kubelet/node.key", 0o600)
    os.chmod("/etc/kubernetes/local-edit.key", 0o600)

    # Generate local-edit kubeconfig (needed for patching PodCIDR later if required)
    print("--> [2/4] Generating temporary kubeconfig for setup...")
    # Note: We use the system's kubectl if available, or we'll rely on the nixos-rebuild to provide it later.
    # For now, we just prepare the config file.
    local_kubeconfig = f"""
apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/pki/ca.crt
    server: {args.api_url}
  name: k8s-manual
contexts:
- context:
    cluster: k8s-manual
    user: kubernetes-local-edit
  name: default
current-context: default
users:
- name: kubernetes-local-edit
  user:
    client-certificate: /etc/kubernetes/local-edit.crt
    client-key: /etc/kubernetes/local-edit.key
"""
    with open("/etc/kubernetes/local-edit.conf", "w") as f:
        f.write(local_kubeconfig)

    # Step 3: Generate NixOS Configuration
    print("--> [3/4] Generating NixOS configuration module...")
    
    # Extract masterAddress from api_url
    master_address = args.api_url.replace("https://", "").replace("http://", "").split(":")[0]

    kubelet_labels = "node.kubernetes.io/kube-proxy-ds-ready=true"
    if args.labels:
        kubelet_labels += f",{args.labels}"
    
    provider_id_opt = f'\n      providerId = "{args.provider_id}";' if args.provider_id else ""
    cluster_cidr_opt = f'\n    clusterCidr = "{args.pod_cidr}";' if args.pod_cidr else ""

    # Bridge CNI logic
    pod_cidr = args.pod_cidr
    cni_nix_config = ""
    if pod_cidr:
        cni_nix_config = f"""
  services.kubernetes.kubelet.cni.config = [
    {{
      "cniVersion" = "0.3.1";
      "name" = "bridge";
      "type" = "bridge";
      "bridge" = "cni0";
      "isGateway" = true;
      "ipMasq" = true;
      "ipam" = {{
        "type" = "host-local";
        "ranges" = [
          [ {{ "subnet" = "{pod_cidr}"; }} ]
        ];
        "routes" = [ {{ "dst" = "0.0.0.0/0"; }} ];
      }};
    }}
  ];
"""

    nix_config = f"""# Auto-generated by setup_node.py
{{ config, lib, pkgs, ... }}:
{{
  boot.kernelModules = [ "overlay" "br_netfilter" ];
  boot.kernel.sysctl = {{
    "net.bridge.bridge-nf-call-iptables" = lib.mkForce 1;
    "net.ipv4.ip_forward" = lib.mkForce 1;
    "net.bridge.bridge-nf-call-ip6tables" = lib.mkForce 1;
  }};

  swapDevices = lib.mkForce [];

  virtualisation.containerd = {{
    enable = true;
    settings = {{
      plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options.SystemdCgroup = true;
    }};
  }};

  services.kubernetes = {{
    roles = [ "node" ];
    masterAddress = "{master_address}";{cluster_cidr_opt}

    # Explicitly disable flannel as we use bridge CNI or GKE manages it
    flannel.enable = lib.mkForce false;

    kubelet = {{
      enable = true;
      hostname = lib.mkForce "{node_name}";
      kubeconfig = {{
        server = "{args.api_url}";
        caFile = "/etc/kubernetes/pki/ca.crt";
        certFile = "/var/lib/kubelet/node.crt";
        keyFile = "/var/lib/kubelet/node.key";
      }};
      clusterDns = "{args.cluster_dns_ip}";
      extraOpts = "--node-labels={kubelet_labels} --v=2";{provider_id_opt}
    }};

    proxy = {{
      enable = true;
      hostname = lib.mkForce "{node_name}";
      kubeconfig = {{
        server = "{args.api_url}";
        caFile = "/etc/kubernetes/pki/ca.crt";
        certFile = "/var/lib/kubelet/node.crt";
        keyFile = "/var/lib/kubelet/node.key";
      }};
    }};
  }};
{cni_nix_config}
  # Ensure kubectl is available for debugging
  environment.systemPackages = [ pkgs.kubectl ];
}}
"""
    with open("/etc/nixos/kubernetes-node.nix", "w") as f:
        f.write(nix_config)

    # Ensure it's imported in configuration.nix
    if os.path.exists("/etc/nixos/configuration.nix"):
        with open("/etc/nixos/configuration.nix", "r") as f:
            content = f.read()
        if "./kubernetes-node.nix" not in content:
            print("  [i] Adding import to /etc/nixos/configuration.nix...")
            # Simple insertion before the last closing brace or in imports list
            if "imports = [" in content:
                new_content = content.replace("imports = [", "imports = [\n    ./kubernetes-node.nix")
            else:
                new_content = content.rstrip().rstrip('}') + "\n  imports = [ ./kubernetes-node.nix ];\n}"
            with open("/etc/nixos/configuration.nix", "w") as f:
                f.write(new_content)

    # Step 4: Apply Configuration
    print("--> [4/4] Applying NixOS configuration (nixos-rebuild switch)...")
    run_command(["nixos-rebuild", "switch"])

    print("\n------------------------------------------------------------------------")
    print("  [SUCCESS] NixOS worker node setup is complete.")
    print("------------------------------------------------------------------------")

if __name__ == "__main__":
    main()
